### ISSUE TITLE
fix dependency security alert 

### ISSUE THREAD

**Issue by dindinw** [Qitmeer/qitmeer.js#12]
Please also update `minimist` to 0.2.1 above and `acorn` to 6.4.1
https://github.com/Qitmeer/qitmeer.js/network/alerts

**Comment by zhangyi999** [comment]
https://github.com/Qitmeer/qitmeer.js/pull/13

**Comment by dindinw** [comment]
@zhangyi999 when composing your PR, you can write your PR description using the keywords like 'fix #13" or "close #13",  so that the issue can be closed automatically by Github. see https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue for details. 
Please close the issue if everything is fine.
