### ISSUE TITLE
fix security warnning

### ISSUE THREAD

**Issue by dindinw** [Qitmeer/qitmeer.js#24]
Dependabot cannot update serialize-javascript to a non-vulnerable version
The latest possible version that can be installed is 3.0.0 because of the following conflicting dependency:

mocha@8.0.1 requires serialize-javascript@3.0.0
The earliest fixed version is 3.1.0.

View logs or learn more about troubleshooting Dependabot errors.

**Comment by zhangyi999** [comment]
The 0.1 branch has upgraded this issue

**Comment by gzh1612** [comment]
Security warning fixed
And configure the dependbot
Submit pull request

**Comment by dindinw** [comment]
fixed by #26
